### ISSUE TITLE
Instead of collaborating or supporting me, you guys stole my idea

### ISSUE THREAD

**Issue by ozramos** [google/project-gameface#1]
About a year or 2 ago Lawrence Maloney @lmoroney asked me about my project Handsfree.js (https://github.com/ozramos/handsfree) and if it could be used for accessibility. I showed him that not only could it, but that I've already open sourced a gesture mapper and desktop controller, that is itself handsfree, using a block based interface called Midiblocks: https://github.com/ozramos/midiblocks and https://midiblocks.firebaseapp.com. The worst part is that after I asked him for support, he didn't respond...he just took all my notes and ghosted me

https://github.com/google/project-gameface/assets/69949201/0c2bdb0c-6c18-4cb0-b6e4-7ac476ab3913

I'm very upset with this team right now, because I started working on these efforts while homeless in 2018 to help someone at the shelter recovering from a stroke. I didn't even have my own computer and was using a library computer to develop this, until Google PAIR gave me a computer. Here is proof of me at the shelter after hanging out with them (there's a local office)

![image](https://github.com/google/project-gameface/assets/69949201/1d7eea81-aef4-4bc6-a911-c88936fd9982)

I have been living in poverty for all of these years, to the point of professors sending me food boxes at my lowest points. And still I've been obsessively pushing out dozens of projects, tutorials, and examples: https://oz.super.site/handsfreejs (unfortunately I burned out last year from extreme stress and deleted my entire body of work, this is just the stuff I have. My repos also had thousands of stars)

My hands are shaking and I'm crying right now because for years and years and years I've lived in isolation and struggled severely, in and out of mental health hospitals, for no reason at all...you could have supported my work. You still can support my work and you don't...I don't understand why it's not like I haven't asked many of you directly for help

I am so obsessively passionate about my research and work that I pursued it fully and blindly, instead of wasting time making other people money building things that don't ultimately matter. I could have been working with you, I prototyped these tools years ago!

On the one hand I feel validated, on the other hand if I tell anyone outside of this repo any of this they'll put me back in the loony bin thinking I'm making all this up. I have literally had to have hospitals call a professor at Carnegie Mellon to verify my story because they thought I was making all this up ("this" being my journey in making this and they just thought I was "manic")

In the recently leaked memo from Google about "AI moats", there was a bit saying something like open source is a huge competitor to you and OpenAI because so many quote "regular people" are contributing ideas...there's nothing regular about the efforts of people like myself who furiously and passionately contribute

Despite my anger and disappointment, I do congratulate you on finally making progress on this. The video for the blog was genuinely beautiful and moving and I do have shame for having these negative emotions. I can't hold a job and will never make money for anything I have built, but I think seeing this project will ease my depression because now I know that my ideas are valid and it's just a matter of weathering the poverty

**Comment by ozramos** [comment]
I've closed the issue both literally and metaphorically, I think this and related projects are beautiful but I think you guys could be much more supportive and acknowledging of the open source community. Not simply liking a tweet or repo but really going hardcore and lifting people up

I posted this out of frustration because Laurence reached out while I was homeless and ghosted me after I asked why not just support my efforts since I had already made so much progress, and open sourced it all

This is one of the many examples and repos I showed him. Not only am I playing hands-free, I mapped the gestures handsfree and am controlling the desktop from the browser...it's handsfree end-to-end (except for literally turning the computer on) and this was in 2019-2020.

https://github.com/google/project-gameface/assets/69949201/0740d9f6-b25b-4836-959c-3f60c847c469

**Comment by golanlevin** [comment]
![FufZcc2aMAAU3Mm-1](https://github.com/google/project-gameface/assets/290053/f61a9893-34b6-4bb0-aea0-f6c39ea74579)

Oz has closed this issue. But on his behalf, here's a word of coda — so that his voice might not be diminished. 

I see some folks are praising Google for their high-mindedness in creating Project Gameface to help the disabled. It's a cruel tragedy that Google did this — _factually_ — on the back of Oz Ramos, a homeless Iraq war veteran, who has PTSD, who created the working prototype on which the design of Project Gameface is based. Bluntly, **Oz Ramos's [Handsfree.js](https://github.com/ozramos/handsfree) project, which he had been developing since 2018, was plagiarized by Google for its Project Gameface**. Oz has a posse, you see. So, here are some receipts. 

I'm a [Professor of electronic art](http://www.art.cmu.edu/people/golan-levin/) and [computer science](https://csd.cmu.edu/people/faculty/golan-levin) at Carnegie Mellon University, and I can affirm that Oz's story and allegation are true. I supported Oz's work on Handsfree.js through [residencies](https://studioforcreativeinquiry.org/project/spring-2021-ossta-residencies) at my lab, the STUDIO for @creativeinquiry at CMU, in February 2019 and February 2021. I'm the professor that Oz refers to, above. 

Oz was inspired to begin working on what became Handsfree.js in 2018, when he was staying at a homeless shelter. Oz met another resident at the shelter, who was recovering from a severe stroke that left them unable to communicate with their friends and family. From 2018 through 2023 — as a self-taught software developer with no college degree — Oz worked on Handsfree.js whenever his circumstances allowed. He tested it with other veterans. He made it work in the browser, and across multiple platforms. He connected it to toolkits for programming education, like p5.js from the @processing Foundation. He received support to continue developing the project from @glitchdotcom, @OpenSourceArts, and @pair-code (Google PAIR). He continued to work on it, even after his laptop was stolen. He did this while surviving on less than $12K per year, _total_, in Veteran Disability Benefits. Always, his vision was for Handsfree.js to build accessible interfaces for disabled people.

Lawrence Maloney @lmoroney contacted Oz more than a year ago. Lawrence extracted a full rundown of how Handsfree.js worked; learned about Oz's ambitions for his passion project; and learned about Oz's sidecar [MidiBlocks](https://oz.super.site/midiblocks) project, which allows people to design their own game-controlling macros and shortcuts for Handsfree.js. You can see some of this work in the GIF below. Oz summoned the courage to ask Lawrence for a job or funding to develop the project further...and Lawrence cold ghosted him. Let's just say Oz was at a _pretty low point_ after that.

![195268382-216349f1-b8ae-4942-a809-8d052be720fa_(1)](https://github.com/google/project-gameface/assets/290053/5788b0fe-a82f-439b-9607-dd0d97d0e529)

I've [seen corporations steal the work of individual creators](http://flong.com/archive/blog/2012/new-media-artists-are-the-unpaid-research-division-of-ad-agencies/index.html) more times than I can count, but this case truly takes the prize for its unnecessary and grievous cruelty. This could have _so easily_ been a happy story. Oz was _already_ using Google's MediaPipe as the tracking library in Handsfree.js! Google could have brought in Oz as a contributing consultant, uplifting him as a remarkable and exemplary MediaPipe developer, in a collaborative process to develop a solution for Lance. For pennies. Instead — you callously crushed the spirit of a homeless vet. 

What's done is done, the issue is closed. But I think an apology from the project team, and an official acknowledgement of Oz's contributions to the Gameface project, would still be very welcome.

Here are some more receipts for those interested. 

* https://oz.super.site/handsfreejs — Oz's documentation of Handsfree
* https://handsfreejs.netlify.app/ — An older Handsfree page, from 2021
* https://clinicopensourcearts.com/index.php/portfolio/handsfreejs — Oz's residency at the Clinic for Open-Source Arts
* https://studioforcreativeinquiry.org/project/spring-2021-ossta-residencies — Oz's residency at CMU
* https://dev.to/goinghandsfree/introducing-handsfree-js-integrate-hand-face-and-pose-gestures-to-your-frontend-4g3p — Thorough article on Handsfree.js at Dev.to.
* https://vimeo.com/760693757 — Oz controlling a robot with Handsfree at CMU in 2019

**Comment by steeve** [comment]
I'm a complete stranger but what a great story about Handsfree.js came to be. Congratulations to Oz, very humbling, however sad the situation is.

Google should absolutely respond.

**Comment by christensen143** [comment]
Yet another reason that I am weaning myself off of all of Google's products. "Don't be evil" What an irony.

**Comment by donno2048** [comment]
That's awful! Might be naive but I really thought Google was a "good company" up until now, but what the hell man!

Waiting for a response from Google...

Also, how doesn't it get any news coverage?

**Comment by akamicah** [comment]
Stay classy, Google. Stay classy.

Looks like you've done some amazing work here @ozramos

**Comment by LexiconCode** [comment]
Oz story resonates with me as I came into maintainership of open source software as a self-taught disabled individual. I've struggled with those who have re-implemented closed source software from the open source stack and competing for community members through support channels rather than contributing back. Coming from that burnout experience, here's what I have to say...

To the community: There are better ways to support Oz then demanding an apology from Google. The community should contribute to his financial well-being and collaborate with his work. 

To Oz: I'm sorry and my heart goes out to your story. I hope your situation has improved. It would be nice to be in touch as I share the same passion for that are need that are disadvantaged interacting with technology.

**Comment by QuentinLemCode** [comment]
Is this "[The Billion Dollar Code](https://www.imdb.com/title/tt15392100/)" season 2 ?

This is amazing @ozramos, I hope your work gets the recognition it deserves.

**Comment by entrptaher** [comment]
This is so heartbreaking to read. Such a talented person going through so much for such silly reason. I believe the community should help him. He is a gem, we should not throw this away.

**Comment by ozramos** [comment]
I appreciate all the replies everyone but I closed the issue to not take away from their project. Projects like this are important which is why I worked so hard, but at the end of the day, the passion has been replaced by grief and I'm no longer interested on making it my lifes work

Even the times I've been inpatient at mental health centers (and have had access to a phone) I have coded experiments and art on my phone. I love coding and creating and feeling like I am doing something special so much it makes me want to vomit...being able to express yourself freely is so beautiful to me and it's why I worked so hard to make the web more accessible

For the last few years I've lived in almost total isolation. When I went to my first residency, as I was leaving, I started ugly crying in front of my host from the happiness of having experienced what it's like to be seen and surrounded by people who want to see you succeed. It's still one of the best moments in my life

And that's where I feel Laurence was cruelest because he knew all this. Even Jeff Dean and others at Google retweeted me a bunch...

Anyways, this already took a few hours to write 😅 I appreciate the discourse and the validation here, but my frustration is with Laurence and Google's approach to open source and not with the other individuals working on this or even the project itself

I keep trying to start a new identity for myself but I get panic attacks a few days into starting a new project. This whole experience of working on open source honestly broke me and I don't think I can meaningfully contribute any more in a way that isn't destructive to me...but I also don't think that's the end of the world, there's so much more to research and do outside of code!

This project was a complete accident, I was inspired while homeless to help a friend who had a stroke and I helped him and many others. I know rationally I should be happy with just that and I think if I start treating myself with the same love and care I do for my projects, maybe one day I will be 🙂

**Comment by lmoroney** [comment]
I would like to take a moment to address claims that Project Gameface was inspired by anything other than the incredible story of [Lance Carr](https://www.youtube.com/@gimpyggaming4287). As we’ve mentioned in previously shared documentation, Project Gameface was the direct output of Lance’s experience and a desire to make the world of computing even more accessible. 

When Oz approached me, I was already working on what would become Project Gameface, and had a specific technical problem that I was trying to solve. Oz showed me his impressive demo, and we chatted briefly about the problem I was having. Unfortunately [Handsfree.js](http://handsfree.js/) could not solve it, and thus I didn't use Handsfree.js in any capacity. 

As I mentioned to Oz when we spoke, I wish him the best with his open source work. Finding new ways to make computing more accessible is an important space that I hope many projects are successful in.

**Comment by ozramos** [comment]
You approached me.

> "Finding new ways to make computing more accessible is an important space that I hope many projects are successful in."

So why didn't you help and why did you ghost me when I asked? If you really believed this you would be nearly vomiting from the enthusiasm and all the opportunities you have to actually make it happen. Think about it man, you work at Google...how are you not lifting people up just by existing, there are endless opportunities for you to lift projects and people up you even talk about it in some of your videos!

The reason I worked so stubbornly for years is because everyone, you included, told me not to give up and to keep going. Like, I watch your videos and read your articles! I literally learn from you, I'm in your audience. Instead of just being like here's some basic help and tips you ghosted me.

You and your team have enough resources that you could fund 10 of these projects in tandem along with the schools to teach you how. The truth is, you didn't actually do anything. You are still claiming credit for what your team built, but YOU yourself didn't build anything. You went to meetings, you set milestones, you shared docs, all the stuff I myself did too...except you yourself didn't actually build anything

And yet you are the one who gets rewarded. It doesn't make sense.

I'm going to delete all of my work and accounts, and then I'm going to admit myself to inpatient mental health. The last time I did this I was able to "move on" and started making progress in life and even got a job as a janitor for the hospital. When I code, I can't help but throw myself blindly at the project to the exclusion of everything else.

The problem is that the things I obsess over create no value, I would be in a better place in life right now had I not contributed to this community. Even in therapy, it usually takes half a dozen or so sessions before my therapist believes this insane story. I once had to have a hospital call a professor because they thought I was having a manic episode, they literally said to my face none of this actually happened and that I'm having an episode...

Meanwhile, I didn't just create a library, I created a whole framework for interacting with devices through gestures...I created a utility library, a gesture mapper, key bindings that themselves are hands-free, a MIDI controller, a browser extension for browsing handsfree, dozens of tutorials and integrations...and that's just the basic stuff

Someone at Google once asked me what my motivation is, and I responded that I wanted to create the equivalent of a mouse driver for gesturally interacting with devices, but one that replaces the mouse and keyboard. I told them that I wanted to build something so good it was used on Mars

They laughed but I was serious, I view the mouse and keyboard as a hindrance. It's not just an accessibility issue, it's straight up annoying to have to sit and type and click things meanwhile there's a whole universe around you. My friend at the shelter who had the stroke is what inspired me to start the project, but what kept me working on it was actually the idea of "solving" interacting with devices for all people.

I thought this was a worthwhile goal, and so when people told me not to give up and to keep going I did...even when I was really struggling and even homeless. I really believed this was worthwhile effort, so when you say:

> "Finding new ways to make computing more accessible is an important space that I hope many projects are successful in."

I don't believe you. But unlike you when I say something I really mean it, and I will demonstrate that now by deleting my body of work and admitting myself to a hospital and starting a new life far removed from these communities.

**Comment by lmoroney** [comment]
>>So why didn't you help and why did you ghost me when I asked? <<

As I explained at the time, my team isn't set up to help individuals in the way that you asked. I brought your case before those that can within Google, and left it to them to reach out to you. Indeed, you mentioned (in your first post in this thread) that they already gave you a computer  -- I am not sure when that happened, but those are the folks that do that kind of payment/donation, and not my team. I asked you, at the time, if you had a charity or other organization that you work with, because that would be the only way we would be able to do anything, and maybe not even then, and the answer was 'no'. That's where the conversation ended. 

>>You and your team have enough resources that you could fund 10 of these projects in tandem along with the schools to teach you how. <<

We DO fund many schools that teach people how. They are organizations that we are set up to be able to send funds to. We also fund many other charitable organizations in many ways.

>>I say something I really mean it, and I will demonstrate that now by deleting my body of work and admitting myself to a hospital, and starting a new life far removed from these communities.<<

I'd encourage you NOT to do that for the reasons you are stating. You're clearly talented, and talent can lift you out of any difficult circumstance.

I would also encourage you to go back and read what you have written and see the false accusations in that. You have caused me immeasurable damage with those statements. 

I am very sorry that we could not make things work with handsfree.js in my project(s). There was one very specific problem I was having with the work I was doing with Gameface. I had hoped that handsfree.js could be used to fix it. It couldn't, and that's where the story ended as far as my involvement with your library was concerned. No malice. No theft. No imitation. 

I'm upset that you take that so personally, but I utterly reject your accusations of theft.

**Comment by ozramos** [comment]
When I wrote the initial post I was very emotional, as I was when I responded this morning and also now. I apologize for how heavy and generally for how dark this post is and also for reputation. I used the word stole because it was the closest word to describing what it feels like, not as in you literally took my code.

I took it personally because when you reached out I felt validated during a time when things were dark and I needed validation. I had been learning from you for a long time so when you reached out it felt like I finally "made it", but as I write this, I realize how insane that sounds. And how insane all of this is, actually. I think I've been struggling for so long that it's warped my personality, and I think I see that now in my responses. 

The reason I'm not successful is because of me, not you or anyone else. Opportunities are out there but I keep imploding due to negative self talk. I didn't go to the hospital because after deleting my projects I felt much better, though I did make appointment with therapist.

I'm sorry that this post got any attention at all and I'm sorry for how much emotion I directed at you. The title is how I felt and the post was my attempt to explain why I felt that way. Open Source in general is unnecessarily lacking in support to the point of sometimes being cruel and my point is that it doesn't have to be this way.

**Comment by lmoroney** [comment]
I appreciate those words. Words have power.

You have to understand though, that by posting your _previous_ words publicly, you lit a flame that was fanned by others, leading to third parties that read those words acting as judge, jury, and executioner.
 
 Since the issue was raised on HackerNews -- my life has been hell. Not an hour goes past without some kind of personal attack that ranges from a shaming to an outright physical threat. It has affected my livelihood, my career, and my health. It destroyed a family vacation when I was supposed to unplug. Nobody deserves that, and certainly not someone who is innocent of what they are accused of. Please be aware of that should you ever feel emotional again.

This is not written to make you feel guilty in any way -- you have enough on your plate -- but as a reminder that one simply cannot say what they want online, particularly if it is untrue, and targeting another individual, and not expect there to be consequences.

**Comment by ozramos** [comment]
You definitely don't deserve that and I regret posting this publicly. I regret working on this project at all.

The most beautiful and worst moments of my life happened while developing my projects but I got nowhere with them and even worse the finale was that it caused harm.

People sell farts in bottles and I couldn't even raise enough support for this. But instead of taking ownership of the fact that it was me who was incapable of raising support, I blamed it on my circumstances and blamed it on others (or the lack of others). I expressed myself as honestly as I could, but I did it in such a harmful way that other people reacted and I'm sorry for that.

Even now, people are attacking you but only 1 or 2 people in all these months since posting have actually reached out to me. I haven't read the HackerNews post yet bc I felt embarrassed to share so much and so openly in a GitHub issue only for my pain to be literally amplified to others like this.

I'm sorry I hurt you Laurence. Thank you for your response as it gave me perspective. I deleted all of my repos because I don't want to get excited about an idea and go through all this again. If my life or project were actually meaningful, I would have gotten help...I myself was homeless when I saw other people who needed even more help than me and I guess I just assumed I would get help too.

I didn't do anything to deserve support, but likewise, you didn't do anything to deserve that. I left my email on my page if anyone wants to contact me but I probably won't be doing much of anything anymore.

**Comment by golanlevin** [comment]
In light of Oz's remarks above, I have deleted my previous comment and here **publicly retract my previous statement on this matter**. It's clear that @lmoroney was acting in expected and ethical ways within established parameters. While I feel it was unfortunate (and a missed opportunity for all involved) that there was no means or incentive for Google to incorporate Oz and Handsfree into its Gameface project, Lawrence should not suffer reputational damage for _not_ doing so, and certainly not for working in parallel on a broadly similar and straightforward concept (i.e. the use of facetracking to assist the handicapped). I apologize to @lmoroney for impugning his efforts, and I wish Oz and Lawrence the best.

Golan Levin
Professor of Art
Carnegie Mellon University
